spring.application.name=EMS

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/EMS_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Spring Security
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

#radis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis

#logging filer
# Logging
#logging.level.com.tyss.EMS=INFO

spring.output.ansi.enabled=always

logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%thread]){faint} %clr(%logger{36}){cyan} - %msg%n

# Disable Spring Batch automatic execution on application startup
spring.batch.job.enabled=false

#configuration for Actuator
# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,beans,mappings

# Show health details
management.endpoint.health.show-details=always

# Application information
management.info.env.enabled=true

info.app.name=Employee Management System
info.app.description=EMS using Spring Boot and Spring Batch
info.app.version=1.0.0

#logger
logging.level.root=INFO

logging.level.com.tyss.EMS=TRACE
logging.level.com.tyss.EMS.controller=TRACE
logging.level.com.tyss.EMS.service=TRACE
logging.level.com.tyss.EMS.repository=TRACE
logging.level.com.tyss.EMS.filter=TRACE

#for Redis cache track
logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.cache=TRACE
